- models/dictionaryParcer.js
> remove console.log

- cron.yaml
- models/MarketsFetch.js
- models/ProductsFetch.js
- notes.md
> add cron.yaml

- index.js
- server.js
Add sessions and traders cron to index.js
> add cron jobs to index

- models/dictionaryParcer.js
> update dictionary parcer

- graphQL/resolvers.js
> add console

- knexfile.js
- models/dictionaryParcer.js
- models/graphLabels.js
- notes.md
filter commodityCat and procedure commodity through hardcoded dictionary
> Graph labels dict

- cron.js
- cron.yaml
- cronMarkets.js
- index.js
- models/dictionaryParcer.js
- notes.md
> Remove cron

- models/dictionaryParcer.js
- models/graphLabels.js
> update procduredest and exchangeddirection

- README.md
> add updates to Readme.md

- graphQL/schema.js
- services/EmailService.js
Updates to add nature of inquiry for Contact page.
trello [https://trello.com/c/1l5qycfu/13-contact-page-should-have-nature-of-inquiry-dropdown-sales-data-technical-other](url)
> add nature t onode email

- graphQL/resolvers.js
- graphQL/schema.js
- services/EmailService.js
to confirm email on signup
I combined this with reset password
trello [https://trello.com/c/GcF8T4e1/55-priority-email-verification-welcome-when-creating-account](url)
trello [https://trello.com/c/IrbLwt3M/58-reset-password-backend](url)
> Confirm email on sign up

- graphQL/resolvers.js
> change paypal api

- graphQL/resolvers.js
- models/paypalCancellation.js
- services/accessToken.js
make paypal url a global variable
make abstraction for accessToken
> add accessToken, make env for paypalUrl

- graphQL/resolvers.js
- services/EmailService.js
Cancel paypal subscription
trello [https://trello.com/c/PnFTTDZF/74-cancel-paypal-with-credit-card-or-account](url)
tello [https://trello.com/c/nmIEJuN1/72-billing-date-on-cancel-is-not-correct](url)
send email notice, that account was cancelled and date subscription will expire.
trello [https://trello.com/c/zph1tlMe/73-cancellation-notice-email]
on testing, payment is cancelled in paypal and cancel date is returned correctly on frontend.
> update pp cancel resolver

- models/model.js
> add update completed

- graphQL/resolvers.js
- services/EmailService.js
change email and web link to tradeinsights.sautiafrica.org
> rename to tradersInsights

- services/EmailService.js
Added two emails.
trello [https://trello.com/c/WbH6Uu8L/81-add-kalias-emails-to-backend](url)
> add emails verifyAccount and account cancellation

- graphQL/resolvers.js
- services/EmailService.js
> add paidAccountEmail

- package-lock.json
- package.json
- services/EmailService.js
> update nodemailer to send with token

- services/EmailService.js
> Google email

- models/tradersDataParser.js
- models/tradersDelete.js
> add tradersDelete
